(()=>{'use strict';
const $=id=>document.getElementById(id), video=$('camera67'),canvas=$('motion67'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const intro=$('intro67'),countdown=$('countdown67'),result=$('result67'),scoreEl=$('score67'),timerEl=$('timer67'),bestEl=$('best67'),controls=$('practiceControls67');
let stream=null,raf=0,running=false,practice=false,muted=false,score=0,lastSide='',armed={left:true,right:true},previous=null,startedAt=0,duration=15000,cooldown=0;
const bestKey='vibox-67-best',boardKey='vibox-67-scores';
function scores(){try{return JSON.parse(localStorage.getItem(boardKey)||'[]')}catch{return[]}}
function renderBoard(){const data=scores();$('leaderboard67').innerHTML=(data.length?data:[{score:0,date:'Your first run'}]).slice(0,5).map((x,i)=>`<li><b>${i+1}</b><span>${x.score} points<small>${x.date}</small></span></li>`).join('')}
function saveScore(){const data=scores();data.push({score,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})});data.sort((a,b)=>b.score-a.score);localStorage.setItem(boardKey,JSON.stringify(data.slice(0,10)));localStorage.setItem(bestKey,Math.max(score,+localStorage.getItem(bestKey)||0));bestEl.textContent=localStorage.getItem(bestKey)||0;renderBoard()}
function sound(freq=520){if(muted)return;try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.045,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.08);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.09);setTimeout(()=>a.close(),180)}catch{}}
function point(side){if(!running||side===lastSide||performance.now()<cooldown)return;lastSide=side;cooldown=performance.now()+110;score++;scoreEl.textContent=score;const f=$('flash67');f.textContent=`${side==='left'?'←':'→'} +1`;f.classList.remove('pop');void f.offsetWidth;f.classList.add('pop');sound(score===67?880:480+(score%5)*40);if(score===67)$('view67').classList.add('hit67')}
function zoneMotion(data,w,h,x0,x1){let changed=0,total=0;for(let y=0;y<h*.48;y+=8){for(let x=Math.floor(w*x0);x<w*x1;x+=8){const i=(y*w+x)*4,lum=(data[i]+data[i+1]+data[i+2])/3;const d=previous?Math.abs(lum-previous[(y*w+x)]):0;if(d>32)changed++;total++}}return total?changed/total:0}
function detect(){if(!running||practice)return;const w=160,h=120;if(video.readyState>=2){canvas.width=w;canvas.height=h;ctx.save();ctx.scale(-1,1);ctx.drawImage(video,-w,0,w,h);ctx.restore();const img=ctx.getImageData(0,0,w,h).data,left=zoneMotion(img,w,h,.03,.42),right=zoneMotion(img,w,h,.58,.97),next=new Uint8Array(w*h);for(let i=0,p=0;i<img.length;i+=4,p++)next[p]=(img[i]+img[i+1]+img[i+2])/3;if(previous){if(left<.035)armed.left=true;if(right<.035)armed.right=true;if(left>.085&&armed.left){armed.left=false;point('left')}else if(right>.085&&armed.right){armed.right=false;point('right')}}previous=next}raf=requestAnimationFrame(detect)}
async function camera(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera unavailable');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();video.classList.add('active')}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null}
function hideAll(){intro.hidden=true;countdown.hidden=true;result.hidden=true}
async function begin(usePractice=false){practice=usePractice;hideAll();controls.hidden=!practice;if(!practice){try{await camera()}catch{intro.hidden=false;$('start67').innerHTML='<i class="fas fa-rotate"></i> Camera blocked — try again';return}}countdown.hidden=false;let n=3;$('count67').textContent=n;const tick=setInterval(()=>{n--;if(n){$('count67').textContent=n;return}clearInterval(tick);countdown.hidden=true;startRound()},720)}
function startRound(){score=0;lastSide='';previous=null;armed={left:true,right:true};scoreEl.textContent=0;timerEl.textContent='15.0';startedAt=performance.now();running=true;$('view67').classList.add('playing');if(!practice)detect();raf=requestAnimationFrame(clock)}
function clock(now){if(!running)return;const remain=Math.max(0,duration-(now-startedAt));timerEl.textContent=(remain/1000).toFixed(1);if(remain<=0)return finish();raf=requestAnimationFrame(clock)}
function finish(){running=false;cancelAnimationFrame(raf);$('view67').classList.remove('playing','hit67');controls.hidden=true;stopCamera();saveScore();result.hidden=false;$('final67').textContent=score;$('resultIcon67').textContent=score>=67?'🏆':score>=40?'🔥':'⚡';$('resultTitle67').textContent=score>=67?'You conquered 67!':score>=40?'Seriously fast!':'Round complete!';$('resultCopy67').textContent=score>=67?'Challenge cleared. That was explosive.':`You were ${Math.max(0,67-score)} points away from 67.`;sound(score>=67?980:620)}
async function share(){const text=`I scored ${score} in the 6–7 Camera Challenge on Vibox. Can you reach 67?`;try{if(navigator.share)await navigator.share({title:'6–7 Camera Challenge',text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);$('share67').textContent='Copied!'}}catch{}}
$('start67').addEventListener('click',()=>begin(false));$('practice67').addEventListener('click',()=>begin(true));$('again67').addEventListener('click',()=>{result.hidden=true;intro.hidden=false});$('share67').addEventListener('click',share);$('left67').addEventListener('click',()=>point('left'));$('right67').addEventListener('click',()=>point('right'));$('mute67').addEventListener('click',()=>{muted=!muted;$('mute67').innerHTML=`<i class="fas fa-volume-${muted?'xmark':'high'}"></i>`});
addEventListener('keydown',e=>{if(practice&&running){if(e.key.toLowerCase()==='a')point('left');if(e.key.toLowerCase()==='l')point('right')}});addEventListener('pagehide',stopCamera);bestEl.textContent=localStorage.getItem(bestKey)||0;renderBoard();
})();
