(()=>{'use strict';const $=id=>document.getElementById(id),stateKey='vibox-face-mogged-state',historyKey='vibox-face-mogged-matches';let stream=null,practice=false,metrics={light:76,frame:81,stable:79},structure={symmetry:78,balance:80,clarity:76},elo=1000,wins=0,streak=0,timer=null,voteTimer=null;
function load(){try{const s=JSON.parse(localStorage.getItem(stateKey)||'{}');elo=s.elo||1000;wins=s.wins||0;streak=s.streak||0}catch{}$('eloHero').textContent=elo;$('winsHero').textContent=wins;$('streakHero').textContent=streak;renderHistory()}
function save(match){localStorage.setItem(stateKey,JSON.stringify({elo,wins,streak}));const h=history();h.unshift(match);localStorage.setItem(historyKey,JSON.stringify(h.slice(0,8)));load()}
function history(){try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return[]}}
function renderHistory(){const h=history();$('fmLeaderboard').innerHTML=(h.length?h:[{result:'No matches yet',elo:'—',date:'Start your first battle'}]).map((m,i)=>`<li><b>${String(i+1).padStart(2,'0')}</b><div>${m.result}<small>${m.date}</small></div><span>${m.elo}</span></li>`).join('')}
function show(step,title,label){['cameraStep','scanStep','queueStep','battleStep','resultStep'].forEach(id=>$(id).hidden=id!==step);$('phaseTitle').textContent=title;$('phaseLabel').textContent=label}
async function camera(){stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:960},height:{ideal:720}},audio:false});$('fmVideo').srcObject=stream;await $('fmVideo').play();$('cameraEmpty').hidden=true;$('scanBtn').disabled=false;sample()}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('fmVideo').srcObject=null;$('battleVideo').srcObject=null}
function sample(){const c=$('fmCanvas'),x=c.getContext('2d'),w=c.width,h=c.height;let samples=0,total=0,prev=0,changes=0;const loop=()=>{if(!stream||samples>42)return;x.save();x.scale(-1,1);x.drawImage($('fmVideo'),-w,0,w,h);x.restore();const d=x.getImageData(0,0,w,h).data,g=new Uint8Array(w*h);let sum=0;for(let p=0,i=0;i<d.length;i+=4,p++){g[p]=(d[i]+d[i+1]+d[i+2])/3;sum+=g[p]}const avg=sum/g.length;let mirrorDiff=0,left=0,right=0,edges=0,pairs=0;for(let y=8;y<h-8;y+=3)for(let px=8;px<w/2;px+=3){const a=g[y*w+px],b=g[y*w+(w-1-px)];mirrorDiff+=Math.abs(a-b);left+=a;right+=b;edges+=Math.abs(a-g[y*w+px+2])+Math.abs(b-g[y*w+(w-3-px)]);pairs++}total+=avg;if(prev)changes+=Math.abs(avg-prev);prev=avg;samples++;metrics.light=Math.round(Math.max(35,100-Math.abs(135-total/samples)*.7));metrics.frame=Math.round(Math.max(45,100-Math.abs(left-right)/Math.max(1,pairs)/1.8));metrics.stable=Math.round(Math.max(45,100-changes/Math.max(1,samples)*1.8));structure.symmetry=Math.round(Math.max(42,96-mirrorDiff/Math.max(1,pairs)*.55));structure.balance=Math.round(Math.max(45,metrics.frame));structure.clarity=Math.round(Math.max(45,Math.min(96,48+edges/Math.max(1,pairs)*.35)));updateChecks();requestAnimationFrame(loop)};loop()}
function updateChecks(){$('lightMeter').value=metrics.light;$('frameMeter').value=metrics.frame;$('stableMeter').value=metrics.stable;$('lightValue').textContent=metrics.light>65?'Good':'Improve';$('frameValue').textContent=metrics.frame>65?'Centered':'Adjust';$('stableValue').textContent=metrics.stable>65?'Steady':'Hold still'}
async function enter(usePractice){practice=usePractice;$('arena').hidden=false;$('arena').scrollIntoView({behavior:'smooth'});show('cameraStep','Get battle-ready','01 · CAMERA CHECK');if(practice){metrics={light:78,frame:84,stable:80};structure={symmetry:76,balance:82,clarity:79};updateChecks();$('cameraEmpty').innerHTML='<i class="fas fa-user-shield"></i><b>Practice camera</b><span>No camera permission needed</span>';$('scanBtn').disabled=false}else try{await camera()}catch{$('cameraEmpty').innerHTML='<i class="fas fa-camera-slash"></i><b>Camera unavailable</b><span>Use Play without camera to continue</span>'}}
function scan(){show('scanStep','Private structure scan','02 · ON-DEVICE SCAN');const rating=((structure.symmetry+structure.balance+structure.clarity)/30).toFixed(1);$('ratingValue').textContent=rating;[['Light',structure.symmetry],['Frame',structure.balance],['Presence',structure.clarity]].forEach(([n,v])=>{$('scan'+n).textContent=(v/10).toFixed(1);requestAnimationFrame(()=>$('bar'+n).style.width=v+'%')})}
function queue(){show('queueStep','Matchmaking','03 · 1V1 QUEUE');let dots=0;$('queueCopy').textContent='Scanning ELO range '+(elo-80)+'–'+(elo+80);timer=setInterval(()=>{$('queueCopy').textContent=['Searching the local arena','Opponent found','Locking the matchup'][dots++%3]},650);setTimeout(()=>{if($('queueStep').hidden)return;clearInterval(timer);battle()},2400)}
function battle(){show('battleStep','Structure engine is analyzing','04 · 20-SECOND BATTLE');if(stream){$('battleVideo').srcObject=stream;$('battleVideo').play();$('playerFallback').hidden=true}let remaining=20,progress=0;const userFinal=Math.max(45,Math.min(96,Math.round(structure.symmetry*.4+structure.balance*.3+structure.clarity*.3+(Math.random()*5-2.5)))),rivalFinal=74+Math.floor(Math.random()*15);$('battleTimer').textContent=remaining;$('yourVotes').textContent='SCANNING';$('rivalVotes').textContent='SCANNING';$('viewerCount').textContent='0%';const tick=()=>{remaining--;progress=1-remaining/20;$('battleTimer').textContent=remaining;const visibleUser=Math.round(45+(userFinal-45)*progress),visibleRival=Math.round(45+(rivalFinal-45)*progress);$('yourVotes').textContent=visibleUser.toFixed(1)+' / 100';$('rivalVotes').textContent=visibleRival.toFixed(1)+' / 100';$('voteTrack').style.width=Math.round(progress*100)+'%';$('viewerCount').textContent=Math.round(progress*100)+'%';if(remaining<=0){clearInterval(voteTimer);finish(userFinal>=rivalFinal,userFinal,rivalFinal)}};voteTimer=setInterval(tick,1000)}
function finish(won,y,r){show('resultStep',won?'Victory':'Close battle','05 · RESULT');const delta=won?18+Math.floor(Math.random()*9):-(12+Math.floor(Math.random()*8));elo=Math.max(100,elo+delta);if(won){wins++;streak++}else streak=0;$('matchResult').textContent=won?'YOU WON':'RIVAL WON';$('eloChange').textContent=(delta>0?'+':'')+delta;$('resultSummary').textContent=`Final structure score: ${y.toFixed(1)} to ${r.toFixed(1)}. Your new local ELO is ${elo}.`;save({result:won?'Victory vs RIVAL_304':'Defeat vs RIVAL_304',elo:(delta>0?'+':'')+delta,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})})}
function exit(){clearInterval(timer);clearInterval(voteTimer);stopCamera();$('arena').hidden=true;scrollTo({top:0,behavior:'smooth'})}
async function share(){const text=`My Face Mogged arena ELO is ${elo} with ${wins} wins on Vibox.`;try{if(navigator.share)await navigator.share({title:'Face Mogged',text,url:location.href});else{await navigator.clipboard.writeText(text+' '+location.href);$('shareFm').textContent='Copied!'}}catch{}}
$('enterBtn').onclick=()=>enter(false);$('practiceBtn').onclick=()=>enter(true);$('scanBtn').onclick=scan;$('queueBtn').onclick=queue;$('cancelQueue').onclick=()=>show('scanStep','Private readiness scan','02 · ON-DEVICE SCAN');$('rematchBtn').onclick=queue;$('shareFm').onclick=share;$('exitBtn').onclick=exit;$('rulesBtn').onclick=()=>$('how').scrollIntoView({behavior:'smooth'});addEventListener('pagehide',stopCamera);load();})();
